/* 
drop table if exists Public."review";
drop table if exists Public."friends";
drop table if exists Public."checkin";
drop table if exists Public."users";
drop table if exists Public."categories";
drop table if exists Public."hours";
drop table if exists Public."attributes";
drop table if exists Public."business";

select * into business_bak
from Public."Business"
select * from Public."businessMS1"

copy Public."businessMS1" ("Name","State","City") FROM 'D:\WSU\451 DB\Project\milestone1DB.csv' 
DELIMITER ',' CSV
*/

CREATE TABLE BusinessMS1 (
	name varchar(100),
	state char(2),
	city varchar(30)
);

CREATE TABLE Business (
	BusinessId uuid, 
	Name varchar(100),
	Address varchar(50),
	City  varchar(30),
	State char(2),
	PostalCode varchar(20),
	Latitude Decimal(12,9),
	Longitude Decimal(12,9),
	Stars Decimal(4,2),
	ReviewCount int,
	IsOpen bit,
	PRIMARY KEY (BusinessId)
);

CREATE TABLE Categories (
	Id int GENERATED BY DEFAULT AS IDENTITY, 
	BusinessId uuid NOT NULL,  
	CategoryName varchar(20),
	PRIMARY KEY (Id),
	FOREIGN KEY (BusinessId) REFERENCES Public.Business(BusinessId)
);

CREATE TABLE Hours (
	Id int GENERATED BY DEFAULT AS IDENTITY, 
	BusinessId uuid NOT NULL,  
	WeekDay varchar(10),
	StartTime varchar(15),
	EndTime varchar(15),
	PRIMARY KEY (Id),
	FOREIGN KEY (BusinessId) REFERENCES Public.Business(BusinessId)
);

CREATE TABLE Attributes (
	Id int GENERATED BY DEFAULT AS IDENTITY, 
	BusinessId uuid NOT NULL,  
	AttributeName varchar(40),
	AttributeValue varchar(20),
	PRIMARY KEY (Id),
	FOREIGN KEY (BusinessId) REFERENCES Public.Business(BusinessId)
);

CREATE TABLE Checkin (
	Id int GENERATED BY DEFAULT AS IDENTITY, 
	BusinessId uuid NOT NULL,  
	CheckinWeekDay varchar(10),
	CheckinHour varchar(5),
	CheckinCount smallint,
	PRIMARY KEY (Id),
	FOREIGN KEY (BusinessId) REFERENCES Public.Business(BusinessId)
);

CREATE TABLE Users (
	UserId uuid, 
	Name varchar(30),
	YelpingSince varchar(10),
	ReviewCount int,
	Fans smallint,
	AverageStars decimal(4,2),
	Funny int,
	Useful int,
	Cool int,
	PRIMARY KEY (UserId)
);

CREATE TABLE Friends (
	Id int GENERATED BY DEFAULT AS IDENTITY, 
	UserId uuid NOT NULL,  
	FriendId uuid NOT NULL,  
	AttributeValue varchar(20),
	PRIMARY KEY (Id),
	FOREIGN KEY (UserId) REFERENCES Public.Users(UserId),
	FOREIGN KEY (FriendId) REFERENCES Public.Users(UserId)
);

CREATE TABLE Review (
	ReviewId uuid,  
	UserId uuid NOT NULL, 
	BusinessId uuid NOT NULL, 
	Stars smallint,
	ReviewDate varchar(10),
	Text varchar(1200),
	Useful smallint,
	Funny smallint,
	Cool smallint,
	PRIMARY KEY (ReviewId),
	FOREIGN KEY (UserId) REFERENCES Public.Users(UserId),
	FOREIGN KEY (BusinessId) REFERENCES Public.Business(BusinessId)
);