
CREATE TABLE Business (
	BusinessId uuid, 
	Name varchar(100) NOT NULL,
	Address varchar(50) NOT NULL,
	CityId int NOT NULL,
	Stars Decimal(4,2),
	ReviewCount int,
	PRIMARY KEY (BusinessId),
	FOREIGN KEY (CityId) REFERENCES Public.City(CityId)
);

CREATE TABLE Category (
	CategoryId int GENERATED BY DEFAULT AS IDENTITY, 
	CategoryName varchar(20),
	PRIMARY KEY (CategoryId)
);

CREATE TABLE BusinessCategory (
	BusinessId uuid NOT NULL,
	CategoryId int NOT NULL,
	PRIMARY KEY (BusinessId, CategoryId),
	FOREIGN KEY (BusinessId) REFERENCES Public.Business(BusinessId),
	FOREIGN KEY (CategoryId) REFERENCES Public.Category(CategoryId)
);

CREATE TABLE Attributes (
	AttributeId int GENERATED BY DEFAULT AS IDENTITY, 
	AttributeName varchar(40),
	AttributeValue varchar(20),
	PRIMARY KEY (AttributeId)
);

CREATE TABLE BusinessAttributes (
	BusinessId uuid NOT NULL,
	AttributeId int NOT NULL,
	PRIMARY KEY (BusinessId, AttributeId),
	FOREIGN KEY (BusinessId) REFERENCES Public.Business(BusinessId),
	FOREIGN KEY (AttributeId) REFERENCES Public.Attributes(AttributeId)
);

CREATE TABLE CheckIn (
	CheckInId int GENERATED BY DEFAULT AS IDENTITY, 
	CheckinWeekDay varchar(10),
	CheckinHour varchar(5),
	CheckinCount smallint,
	PRIMARY KEY (CheckInId)
);

CREATE TABLE BusinesCheckin (
	CheckInId int NOT NULL,  
	BusinessId uuid NOT NULL,  
	PRIMARY KEY (CheckInId, BusinessId),
	FOREIGN KEY (CheckInId) REFERENCES Public.CheckIn(CheckInId),
	FOREIGN KEY (BusinessId) REFERENCES Public.Business(BusinessId)
);


CREATE TABLE Users (
	UserId uuid, 
	Name varchar(30),
	YelpingSince varchar(10),
	ReviewCount int,
	Fans smallint,
	AverageStars decimal(4,2),
	Funny int,
	Useful int,
	Cool int,
	PRIMARY KEY (UserId)
);

CREATE TABLE Friends (
	FriendId uuid NOT NULL,  
	PRIMARY KEY (FriendId),
	FOREIGN KEY (FriendId) REFERENCES Public.Users(UserId)
);

CREATE TABLE UserFriends (
	UserId uuid NOT NULL,  
	FriendId uuid NOT NULL,  
	PRIMARY KEY (UserId, FriendId),
	FOREIGN KEY (UserId) REFERENCES Public.Users(UserId),
	FOREIGN KEY (FriendId) REFERENCES Public.Friends(FriendId)
);

CREATE TABLE Review (
	ReviewId uuid,  
	Stars smallint,
	ReviewDate varchar(10),
	Text varchar(1200),
	Useful smallint,
	Funny smallint,
	Cool smallint,
	PRIMARY KEY (ReviewId)
);

CREATE TABLE BusinessReview (
	ReviewId uuid,  
	UserId uuid NOT NULL, 
	BusinessId uuid NOT NULL, 
	PRIMARY KEY (ReviewId,UserId,BusinessId),
	FOREIGN KEY (ReviewId) REFERENCES Public.Review(ReviewId),
	FOREIGN KEY (UserId) REFERENCES Public.Users(UserId),
	FOREIGN KEY (BusinessId) REFERENCES Public.Business(BusinessId)
);

CREATE TABLE PostalCodeData (
	PostalCode char(5),
	MedianIncome int NULL,
	MeanIncome int NULL,
	Population int NULL,
	PRIMARY KEY (PostalCode)
);

CREATE TABLE City (
	CityId int GENERATED BY DEFAULT AS IDENTITY, 
	City  varchar(30) NOT NULL,
	State char(2) NOT NULL,
	PRIMARY KEY (CityId)
);

CREATE TABLE CityPostalCode (
	CityId  int,
	PostalCode char(5) NOT NULL,
	PRIMARY KEY (CityId, PostalCode),
	FOREIGN KEY (CityId) REFERENCES Public.City(CityId),
	FOREIGN KEY (PostalCode) REFERENCES Public.PostalCodeData(PostalCode)
);




